export const FUZZY_AUTO_APPLY_THRESHOLD = 0.85;
export const FUZZY_SUGGEST_THRESHOLD = 0.7;
export const FREE_TIER_SCANS_PER_MONTH = 10;
export const FREE_TIER_MAX_CATEGORY_DEPTH = 3;
export const FREE_TIER_REPORT_HISTORY_MONTHS = 3;

export const DEFAULT_CATEGORY_COLOR = '#6B7280';
export const DEFAULT_CATEGORY_ICON = 'tag';

export const DATE_FORMAT = 'YYYY-MM';
